# Generated by Django 4.2.5 on 2023-10-21 12:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='job__title', unique=True)),
                ('num_applicants', models.PositiveIntegerField(default=0)),
                ('num_selected', models.PositiveIntegerField(default=0)),
                ('applicants', models.ManyToManyField(blank=True, related_name='job_reports', to='employers.applicants')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employers.job')),
                ('selected', models.ManyToManyField(blank=True, related_name='job_reports', to='employers.selected')),
            ],
        ),
    ]
