# Generated by Django 4.2.5 on 2023-11-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_profile_gender'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('grad_year__lte', 2027)), name='valid_grad_year'),
        ),
    ]
